name: healthcafe_dashboard
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.13.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  shared_preferences: ^2.1.2
  firebase_storage: ^11.2.3
  dio: ^5.0.0
  cloud_firestore: ^4.3.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  flutter_dotenv: ^5.1.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins_fonts/Poppins-Black.ttf
        - asset: fonts/poppins_fonts/Poppins-BlackItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-Bold.ttf
        - asset: fonts/poppins_fonts/Poppins-BoldItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-ExtraBold.ttf
        - asset: fonts/poppins_fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-ExtraLight.ttf
        - asset: fonts/poppins_fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-Italic.ttf
        - asset: fonts/poppins_fonts/Poppins-Light.ttf
        - asset: fonts/poppins_fonts/Poppins-LightItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-Medium.ttf
        - asset: fonts/poppins_fonts/Poppins-MediumItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-Regular.ttf
        - asset: fonts/poppins_fonts/Poppins-SemiBold.ttf
        - asset: fonts/poppins_fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/poppins_fonts/Poppins-Thin.ttf
        - asset: fonts/poppins_fonts/Poppins-ThinItalic.ttf
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Black.ttf
        - asset: fonts/inter/Inter-Bold.ttf
        - asset: fonts/inter/Inter-ExtraBold.ttf
        - asset: fonts/inter/Inter-ExtraLight.ttf
        - asset: fonts/inter/Inter-Light.ttf
        - asset: fonts/inter/Inter-Medium.ttf
        - asset: fonts/inter/Inter-Regular.ttf
        - asset: fonts/inter/Inter-SemiBold.ttf
        - asset: fonts/inter/Inter-Thin.ttf
    - family: Visibility
      fonts:
        - asset: fonts/visibility.ttf


  uses-material-design: true
  assets:
    - assets/img/
    - assets/gifs/
    - .env
    - .env.dev
    - .env.stage